# Numpy BASICS

In [1]:
import numpy as np

#### Creating ndarrays


In [3]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

In [4]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [6]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
# dimensions
arr2.ndim

2

In [8]:
# Shape
arr2.shape

(2, 4)

In [9]:
# Datatype 
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int64')

In [12]:
#new array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
#  function in NumPy creates a new array without initializing its elements to any specific values. It allocates memory for the array but doesn't set the values of the array elements. 
np.empty((2,3,2))

array([[[0.00000000e+000, 1.00937611e-320],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 4.47032019e-038]],

       [[5.88731663e-091, 4.18201639e-062],
        [1.56087936e+184, 6.15318677e+170],
        [3.99910963e+252, 2.65714711e-312]]])

In [18]:
# arange is an array-valued version of the built-in Python range function
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int32')

In [26]:
#datatype explicitly convert
arr = np.array([1,2,3,4,5,6])
arr.dtype

dtype('int64')

In [27]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5., 6.])

In [29]:
#integers were cast to floating poin
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.dtype

dtype('float64')

In [31]:
int_arr = arr.astype(np.int32)
int_arr

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [35]:
# converting string to numeric
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [38]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array = int_array.astype(calibers.dtype)
int_array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arrays are important because they enable you to express batch operations on data without writing any for loops. This is usually called vectorization.