# Numpy BASICS

In [67]:
import numpy as np

#### Creating ndarrays


In [68]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

In [69]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [70]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [71]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
# dimensions
arr2.ndim

2

In [73]:
# Shape
arr2.shape

(2, 4)

In [74]:
# Datatype 
arr1.dtype

dtype('float64')

In [75]:
arr2.dtype

dtype('int64')

In [76]:
#new array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [78]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
#  function in NumPy creates a new array without initializing its elements to any specific values. It allocates memory for the array but doesn't set the values of the array elements. 
np.empty((2,3,2))

array([[[4.9e-324, 9.9e-324],
        [1.5e-323, 2.0e-323],
        [2.5e-323, 3.0e-323]],

       [[3.5e-323, 4.0e-323],
        [4.4e-323, 4.9e-323],
        [5.4e-323, 5.9e-323]]])

In [80]:
# arange is an array-valued version of the built-in Python range function
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [81]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)
arr1.dtype

dtype('float64')

In [82]:
arr2.dtype

dtype('int32')

In [83]:
#datatype explicitly convert
arr = np.array([1,2,3,4,5,6])
arr.dtype

dtype('int64')

In [84]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5., 6.])

In [85]:
#integers were cast to floating poin
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.dtype

dtype('float64')

In [86]:
int_arr = arr.astype(np.int32)
int_arr

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [87]:
# converting string to numeric
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [88]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array = int_array.astype(calibers.dtype)
int_array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arrays are important because they enable you to express batch operations on data without writing any for loops. This is usually called vectorization.

In [89]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [90]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [91]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [93]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [94]:
#Indexing and Slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr[5]

5

In [96]:
arr[5:8]

array([5, 6, 7])

In [97]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [98]:
arr_slice  = arr[5:8]
arr_slice[1] = 1234
arr

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

In [99]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [100]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [101]:
arr2d[0,2]

3

In [102]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [103]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [105]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [106]:
arr3d[1,0,1]

8

In [107]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [108]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])